export const ORDER_CREATE_NEW_ITEM_REQUEST= 'ORDER_CREATE_NEW_ITEM_REQUEST';
export const ORDER_CREATE_NEW_ITEM_SUCCESS= 'ORDER_CREATE_NEW_ITEM_SUCCESS';
export const ORDER_CREATE_NEW_ITEM_FAIL= 'ORDER_CREATE_NEW_ITEM_FAIL';

// Update to pay
export const ORDER_UPDATE_TO_PAY_SUCCESS = 'ORDER_UPDATE_TO_PAY_SUCCESS';
export const ORDER_UPDATE_TO_PAY_FAIL = 'ORDER_UPDATE_TO_PAY_FAIL';

//update order after buy
export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

//get all of user 
export const ORDER_GET_UESR_REQUEST = 'ORDER_GET_UESR_REQUEST';
export const ORDER_GET_UESR_SUCCESS = 'ORDER_GET_UESR_SUCCESS';
export const ORDER_GET_UESR_FAIL = 'ORDER_GET_UESR_FAIL';
