export const PRODUCT_ALL_REQUEST = 'PRODUCT_ALL_REQUEST';
export const PRODUCT_ALL_SUCCESS = 'PRODUCT_ALL_SUCCESS';
export const PRODUCT_ALL_FAIL = 'PRODUCT_ALL_FAIL';

// create 

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';

// update

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

//delete
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

//get top product
export const PRODUCT_GET_TOP_REQUEST = 'PRODUCT_GET_TOP_REQUEST';
export const PRODUCT_GET_TOP_SUCCESS = 'PRODUCT_GET_TOP_SUCCESS';
export const PRODUCT_GET_TOP_FAIL = 'PRODUCT_GET_TOP_FAIL';

//get hot product 

export const PRODUCT_GET_HOT_REQUEST = 'PRODUCT_GET_HOT_REQUEST';
export const PRODUCT_GET_HOT_SUCCESS = 'PRODUCT_GET_HOT_SUCCESS';
export const PRODUCT_GET_HOT_FAIL = 'PRODUCT_GET_HOT_FAIL';

// get product by id
export const PRODUCT_GET_BY_ID_REQUEST = 'PRODUCT_GET_BY_ID_REQUEST';
export const PRODUCT_GET_BY_ID_SUCCESS = 'PRODUCT_GET_BY_ID_SUCCESS';
export const PRODUCT_GET_BY_ID_FAIL = 'PRODUCT_GET_BY_ID_FAIL';

//create a new review
export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';