export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';


export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

// admin

export const ADMIN_GET_USERS_REQUEST = 'ADMIN_GET_USERS_REQUEST';
export const ADMIN_GET_USERS_SUCCESS = 'ADMIN_GET_USERS_SUCCESS';
export const ADMIN_GET_USERS_FAIL = 'ADMIN_GET_USERS_FAIL';

export const ADMIN_UPDATE_USERS_REQUEST = 'ADMIN_UPDATE_USERS_REQUEST';
export const ADMIN_UPDATE_USERS_SUCCESS = 'ADMIN_UPDATE_USERS_SUCCESS';
export const ADMIN_UPDATE_USERS_FAIL = 'ADMIN_UPDATE_USERS_FAIL';

export const ADMIN_DELETE_USERS_REQUEST = 'ADMIN_DELETE_USERS_REQUEST';
export const ADMIN_DELETE_USERS_SUCCESS = 'ADMIN_DELETE_USERS_SUCCESS';
export const ADMIN_DELETE_USERS_FAIL = 'ADMIN_DELETE_USERS_FAIL';